name: 'Checkout with full git history'
description: 'Checkout code with full history, branches, and tags'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all branches and tags
      shell: bash
      run: |
        git fetch origin "+refs/heads/*:refs/remotes/origin/*"
        git fetch origin "+refs/tags/*:refs/tags/*"